repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        args: [--check, --config=./poetry/pyproject.toml]
  - repo: local
    hooks:
      - id: check-migrations
        name: Check for missing migrations
        entry: python manage.py makemigrations --check --dry-run --no-input
        language: system
        pass_filenames: false
        files: 'models\.py$'